# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5278ee9bff85303628ad395e9db28ed2ce2f0c1638ce8653c1d48b11cc7094906457704b622957bb7c30863f3e34a50e91e08360f9ff306f99abf63069f0e6aa

test:
  secret_key_base: 2ee05886823224c08f98f182f5652674a0fa1250f242c1f7e3e8777b5b5ae2bbf87f0e48c7e8e2216a8114f01884db0768c0b3bd591d48e2237c843e458036c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
